replicaCount: 1
tssname: tss-node1
image:
  repository: goatnetwork/goat-relayer
  tag: latest
  pullPolicy: IfNotPresent

  tssrepository: goatnetwork/goat-tss
  tssTag: latest
  tssPullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: p2p
      port: 4001
      targetPort: 4001
  tssports:
  - name: tss-http
    port: 8180
    targetPort: 8180
    nodePort: 8180
  - name: tss-p2p
    port: 9009
    targetPort: 9009
    nodePort: 9009
persistence:
  size: 10Gi
  storageClass: ""


envFromSecrets:

nodeAffinity:
  enabled: false
  name: zkm
hostNetwork: true
serviceAccount: mainnet-secret

mountsecret:
  enable: false
  secretProviderClass: mainnet-secrets
  secretName: awscredentials

env:
  LIBP2P_BOOT_NODES: "/ip4/192.168.10.2/tcp/4001/p2p/12D3KooWPxRKQ8mrJspeyppXDbh8SdXq27jVD9p1CmVdi8nmPnq6"