apiVersion: v1
kind: Service
metadata:
  name: {{ include "goat-relayer.fullname" . }}
  labels:
    {{- include "goat-relayer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      {{- if and (eq $.Values.service.type "NodePort") (hasKey . "nodePort") }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}

    {{- range .Values.service.tssports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      {{- if and (eq $.Values.service.type "NodePort") (hasKey . "nodePort") }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "goat-relayer.selectorLabels" . | nindent 4 }}