apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "goat-relayer.fullname" . }}
  labels:
    {{- include "goat-relayer.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "goat-relayer.fullname" . }}
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "goat-relayer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goat-relayer.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
{{- if .Values.nodeAffinity }}
  {{- if .Values.nodeAffinity.enabled}}
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: relayerapp
                operator: In
                values:
                -  {{ .Values.nodeAffinity.name }}
  {{- end }}
{{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ .Values.serviceAccount }}
      {{- if .Values.mountsecret }}
      {{- if .Values.mountsecret.enable }}
      volumes:
      - name: tss-config
        configMap:
          name: {{ .Values.tssname }}-configmap
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.mountsecret.secretProviderClass }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- $secretName := .Values.mountsecret.secretName -}}
            {{- range .Values.envFromSecrets }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ . }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /app/db
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
            {{- toYaml .Values.resources.relayer | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.relayer | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.relayer | nindent 12 }}

        - name: {{ .Values.tssname }}
          image: "{{ .Values.tssimage.repository }}:{{ .Values.tssimage.tag }}"
          imagePullPolicy: {{ .Values.tssimage.pullPolicy }}
          ports:
            {{- range .Values.service.tssports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: tss-config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
              readOnly: true
          resources:
            {{- toYaml .Values.resources.tss | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.tss | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.tss | nindent 12 }}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}