{{- if .Values.network.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goat-geth.fullname" . }}-genesis
data:
  geth.json: |-
    {{- .Files.Get (printf "genesis/%s/geth.json" .Values.network.type) | nindent 4 }}
  goat.json: |-
    {{- .Files.Get (printf "genesis/%s/goat.json" .Values.network.type) | nindent 4 }}
{{- end }}