apiVersion: v1
kind: Service
metadata:
  name: {{ include "goat-geth.fullname" . }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "goat-geth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "goat-geth.selectorLabels" . | nindent 4 }}
  ports:
  - name: geth-rpc
    port: {{ .Values.service.gethRpcPort }}
    targetPort: 8545
    protocol: TCP
  - name: goat-grpc
    port: {{ .Values.service.goatGrpcPort }}
    targetPort: 9090
    protocol: TCP
  - name: goat-rpc
    port: {{ .Values.service.goatRpcPort }}
    targetPort: 26657
    protocol: TCP
