apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "goat-geth.fullname" . }}
  labels:
    {{- include "goat-geth.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "goat-geth.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "goat-geth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goat-geth.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
{{- if .Values.podAntiAffinity }}
  {{- if .Values.podAntiAffinity.enabled}}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - goat-geth
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: goatapp
                operator: In
                values:
                - goatgeth
  {{- end }}
{{- end }}
      containers:
      - name: geth
        image: "{{ .Values.image.geth.repository }}:{{ .Values.image.geth.tag }}"
        imagePullPolicy: {{ .Values.image.geth.pullPolicy }}
        args:
        {{- range .Values.geth.args }}
        - {{ . | quote }}
        {{- end }}
        volumeMounts:
        - name: geth-data
          mountPath: /root/.ethereum
        ports:
        - name: geth-rpc
          containerPort: 8545
        resources:
{{ toYaml .Values.resources | indent 12 }}
        livenessProbe:
          exec:
            command: ["geth", "attach", "--exec", "eth.blockNumber"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5

      - name: goat
        image: "{{ .Values.image.goat.repository }}:{{ .Values.image.goat.tag }}"
        imagePullPolicy: {{ .Values.image.goat.pullPolicy }}
        args:
        {{- range .Values.goat.args }}
        - {{ . | quote }}
        {{- end }}
        volumeMounts:
        - name: goat-data
          mountPath: /root/.goat
        - name: geth-data
          mountPath: /root/.ethereum
        ports:
        - name: goat-rpc
          containerPort: 26657
        - name: goat-grpc
          containerPort: 9090
        - name: goat-rest
          containerPort: 1317
        resources:
{{ toYaml .Values.resources | indent 12 }}
        readinessProbe:
          exec:
            command: ["goatd", "status"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
  volumeClaimTemplates:
  - metadata:
      name: geth-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.geth.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.geth.size | quote }}
  - metadata:
      name: goat-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.goat.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.goat.size | quote }}