apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "goat-geth.fullname" . }}
  labels:
    {{- include "goat-geth.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "goat-geth.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "goat-geth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goat-geth.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
{{- if .Values.podAntiAffinity }}
  {{- if .Values.podAntiAffinity.enabled}}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - goat-geth
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: goatapp
                operator: In
                values:
                - goatgeth
  {{- end }}
{{- end }}
      containers:
      - name: geth
        image: "{{ .Values.image.geth.repository }}:{{ .Values.image.geth.tag }}"
        imagePullPolicy: {{ .Values.image.geth.pullPolicy }}
        args:
        {{- range .Values.geth.args }}
        - {{ . | quote }}
        {{- end }}
        {{- if .Values.service.gethMetricsPort }}
        - "--metrics"
        - "--metrics.addr=0.0.0.0"
        - "--metrics.port=7300"
        {{- end }}
        volumeMounts:
        - name: geth-data
          mountPath: /root/.ethereum
        ports:
        {{- if .Values.service.gethRpcPort }}
        - name: geth-rpc
          containerPort: 8545
        {{- end }}
        {{- if .Values.service.gethMetricsPort }}
        - name: geth-metrics
          containerPort: 7300
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- if .Values.geth.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command: ["geth", "attach", "--exec", "eth.blockNumber"]
          initialDelaySeconds: {{ .Values.geth.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.geth.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.geth.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.geth.livenessProbe.failureThreshold }}
        {{- end }}

      - name: goat
        image: "{{ .Values.image.goat.repository }}:{{ .Values.image.goat.tag }}"
        imagePullPolicy: {{ .Values.image.goat.pullPolicy }}
        args:
        {{- range .Values.goat.args }}
        - {{ . | quote }}
        {{- end }}
        {{- if .Values.service.goatGrpcPort }}
        - "--grpc.address=0.0.0.0:9090"
        {{- end }}
        {{- if .Values.service.goatRpcPort }}
        - "--rpc.laddr=tcp://0.0.0.0:26657"
        {{- end }}
        volumeMounts:
        - name: goat-data
          mountPath: /root/.goat
        - name: geth-data
          mountPath: /root/.ethereum
        ports:
        {{- if .Values.service.goatRpcPort }}
        - name: goat-rpc
          containerPort: 26657
        {{- end }}
        {{- if .Values.service.goatGrpcPort }}
        - name: goat-grpc
          containerPort: 9090
        {{- end }}
        {{- if .Values.service.goatRestPort }}
        - name: goat-rest
          containerPort: 1317
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- if .Values.goat.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "goatd status | jq -e '.sync_info.catching_up == false'"
          initialDelaySeconds: {{ .Values.goat.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.goat.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.goat.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.goat.readinessProbe.failureThreshold }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: geth-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.geth.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.geth.size | quote }}
  - metadata:
      name: goat-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.goat.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.goat.size | quote }}