# Common configuration
image:
  goat:
    repository: ghcr.io/goatnetwork/goat
    tag: testnet
    pullPolicy: IfNotPresent
  geth:
    repository: ghcr.io/goatnetwork/goat-geth
    tag: testnet
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Network configuration
network:
  chainId: 48816

# Goat configuration
goat:
  enabled: true
  args:
    - start
    - --goat.geth=/geth/geth.ipc
    - --goat.preset=bootnode,rpc
    - --chain-id=goat-testnet3

# Geth configuration
geth:
  enabled: true
  args:
    - --goat=testnet3
    - --goat.preset=bootnode,rpc
    - --gcmode=archive

# Persistent storage
persistence:
  enabled: true
  geth:
    storageClass: "local-path"
    size: 50Gi
  goat:
    storageClass: "local-path"
    size: 50Gi

network:
  type: testnet3 # regtest, testnet, mainnet
  enabled: true
  data:
    goat.json
    geth.json

# Service configuration
service:
  type: ClusterIP
  goatGrpcPort: 9090
  goatRpcPort: 26657
  gethRpcPort: 8545
  annotations: {}
