# Common configuration
image:
  goat:
    repository: ghcr.io/goatnetwork/goat
    tag: testnet
    pullPolicy: IfNotPresent
  geth:
    repository: ghcr.io/goatnetwork/goat-geth
    tag: testnet
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 5000m
    memory: 10240Mi

replicas: 3

podAntiAffinity:
  enabled: false

# Network configuration
network:
  chainId: 48816

# Goat configuration
goat:
  args:
    - start
    - --goat.geth=/root/.ethereum/geth.ipc
    - --goat.preset=bootnode,rpc
    - --chain-id=goat-testnet3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 5

# Geth configuration
geth:
  args:
    - --goat=testnet3
    - --goat.preset=bootnode,rpc
    - --gcmode=archive
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 5

# Node Roles represent the different roles a node can have in the network
nodeRoles:
  bootnode:
    enabled: true
    gethNodekeyPath: /root/.ethereum/nodekey
    goatNodekeyPath: /root/.goat/nodekey
  validator:
    enabled: true
  rpc:
    enabled: true

# Persistent storage
persistence:
  geth:
    storageClass: "local-path"
    size: 100Gi
  goat:
    storageClass: "local-path"
    size: 100Gi

network:
  type: testnet3 # regtest, testnet, mainnet

# Service configuration
service:
  type: ClusterIP
  goatGrpcPort: 9090
  goatRpcPort: 26657
  goatRestPort: 1317
  gethRpcPort: 8545
  gethMetricsPort: 7300
  annotations: {}
