# Common configuration
image:
  goat:
    repository: ghcr.io/goatnetwork/goat
    tag: testnet
    pullPolicy: IfNotPresent
  geth:
    repository: ghcr.io/goatnetwork/goat-geth
    tag: testnet
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

replicas: 3

# Network configuration
network:
  chainId: 48816

# Goat configuration
goat:
  args:
    - start
    - --goat.geth=/root/.ethereum/geth.ipc
    - --goat.preset=bootnode,rpc
    - --chain-id=goat-testnet3

# Geth configuration
geth:
  args:
    - --goat=testnet3
    - --goat.preset=bootnode,rpc
    - --gcmode=archive

# Node Roles represent the different roles a node can have in the network
nodeRoles:
  bootnode:
    enabled: true
    gethNodekeyPath: /root/.ethereum/nodekey
    goatNodekeyPath: /root/.goat/nodekey
  validator:
    enabled: true
  rpc:
    enabled: true

# Persistent storage
persistence:
  geth:
    storageClass: "local-path"
    size: 50Gi
  goat:
    storageClass: "local-path"
    size: 50Gi

network:
  type: testnet3 # regtest, testnet, mainnet
  data:
    goat.json
    geth.json

# Service configuration
service:
  type: ClusterIP
  goatGrpcPort: 9090
  goatRpcPort: 26657
  goatRestPort: 1317
  gethRpcPort: 8545
  gethMetricsPort: 7300
  annotations: {}
