# Common configuration
image:
  goat:
    repository: ghcr.io/goatnetwork/goat
    tag: testnet
    pullPolicy: IfNotPresent
  geth:
    repository: ghcr.io/goatnetwork/goat-geth
    tag: testnet
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Network configuration
network:
  chainId: 48815

# Goat configuration
goat:
  enabled: true
  args:
    - --home
    - /goat
    - --goat.geth
    - /root/.ethereum/geth.ipc
    - --api.enable
    - --api.address=tcp://0.0.0.0:1317
    - --p2p.persistent_peers
    - c9befb6b8421b46ec5cda76171a8cf7539af20fc@52.12.249.134:26656
    - --log_level=debug

# Geth configuration
geth:
  enabled: true
  args:
    - --http
    - --http.api=eth,net,web3
    - --http.addr=0.0.0.0
    - --http.vhosts=*
    - --http.corsdomain=*
    - --syncmode=full
    - --bootnodes=enode://0d41d098846751f0f90ea66e4d7e6741591e9c4bfb6e75d14f78ca3702415fb795adad64b2805f428c86f6ae2ee5315322301e02c63c917f92756a909679599e@52.12.249.134:30303
    - --log.debug

# Role configuration
roles:
  rpc:
    enabled: false
    replicas: 1
    extraArgs:
      goat: []
      geth: []
  validator:
    enabled: false
    replicas: 1
    extraArgs:
      goat:
        - "--validator"
      geth:
        - "--mine"
        - "--miner.etherbase=0x0000000000000000000000000000000000000000"
  relayer:
    enabled: false
    replicas: 1
    extraArgs:
      goat:
        - "--relayer"
      geth: []

# Persistent storage
persistence:
  enabled: true
  geth:
    storageClass: "local-path"
    size: 50Gi
  goat:
    storageClass: "local-path"
    size: 50Gi

network:
  type: testnet # regtest, testnet, mainnet
  enabled: true
  data:
    goat.json
    geth.json

# Service configuration
service:
  type: ClusterIP
  goatPort: 26657
  gethPort: 8545